name: Capability Module
on:
  push:
    pull_request:
      - '.github/workflows/capability.yml'
      - 'modules/capability/**'
      - 'proto/capability/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-arch: ["amd64", "arm", "arm64"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Build capability-module
        run: |
          cd modules/capability
          GOARCH=${{ matrix.go-arch }} go build ./...

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Go Test
        run: |
          cd modules/capability
          go test -v -mod=readonly ./...
